### ISSUE TITLE
点个 Star ，留个脚印

### ISSUE THREAD

**Issue by Jenway** [maxelblack/coffee-tutorial#14]
_首先原谅我把 Issues 当评论区用_
现在的高中生都这么牛吗 😿 
我记得我是一路从某个博客点友链然后传送到这里，
这一路上我翻一翻这些博客的About ，好多都是中学生，而且大多都是 NOIPer...
额，扯远了，看了看上一次 commit 似乎是去年六月，大概作者估计是忙于学业了，不过我相信总有一天会完成的，
加油哦
P.S. 记得我中学的时候也想学 Java来着, 残念...

**Comment by maxelblack** [comment]
首先感谢支持，这个项目是之前翻 Java 教程的时候发起的，原因就是中文互联网几乎找不到什么靠谱一点的教程...

然而我现在确实忙于学业，空闲写点 Kotlin（现在我全部仓库 Kotlin 的代码量总和已经超过 Java 了），Java 半年没碰了。以后有时间我会尽可能继续写的，但可能也不会写的多好（关于 Java 近一年发布的新东西都忘的差不多了），现在还是主要在用 Kotlin 生态~~因为真的很好用~~。

**Comment by maxelblack** [comment]
如果感兴趣的话欢迎 PR 一起来写这个教程～

**Comment by Jenway** [comment]
我只是个大一菜鸡罢了😎-🕶=🥲，
感兴趣是有的，但我不会 Java ...
嘛，兴许以后就会了呢，
不过当务之急我还是先应付开学期末考吧
